apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: webapp80
spec:
  host: ec2-65-0-225-217.ap-south-1.compute.amazonaws.com
  upstreams:
  - name: webapp80
    service: webapp80
    port: 80
  subroutes:
  - path: /
    action:
     pass: webapp80
  
