apiVersion: v1
items:
- apiVersion: k8s.nginx.org/v1
  kind: VirtualServer
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8s.nginx.org/v1","kind":"VirtualServer","metadata":{"annotations":{},"name":"myapp","namespace":"nginx-ingress"},"spec":{"host":"ec2-65-0-225-217.ap-south-1.compute.amazonaws.com","routes":[{"action":{"return":{"body":"Hello World\n","code":200,"type":"text/plain"}},"path":"/"}]}}
    creationTimestamp: "2024-06-06T06:52:46Z"
    generation: 3
    name: myapp
    namespace: nginx-ingress
    resourceVersion: "5120375"
    uid: e1072476-417e-47fa-a025-c210ca01cc8c
  spec:
    host: ec2-65-0-225-217.ap-south-1.compute.amazonaws.com
    routes:
    - action:
        return:
          body: |
            HELLO from TEST!HELLO from TEST!HELLO from TEST !HELLO from TEST !HELLO from TEST ! Hello from Test
            HELLO from TEST!HELLO from TEST!HELLO from TEST !HELLO from TEST !HELLO from TEST ! Hello from Test
            HELLO from TEST!HELLO from TEST!HELLO from TEST !HELLO from TEST !HELLO from TEST ! Hello from Test
            HELLO from TEST!HELLO from TEST!HELLO from TEST !HELLO from TEST !HELLO from TEST ! Hello from Test
            HELLO from TEST!HELLO from TEST!HELLO from TEST !HELLO from TEST !HELLO from TEST ! Hello from Test
            HELLO from TEST!HELLO from TEST!HELLO from TEST !HELLO from TEST !HELLO from TEST ! Hello from Test
            HELLO from TEST!HELLO from TEST!HELLO from TEST !HELLO from TEST !HELLO from TEST ! Hello from Test
            HELLO from TEST!HELLO from TEST!HELLO from TEST !HELLO from TEST !HELLO from TEST ! Hello from Test
            HELLO from TEST!HELLO from TEST!HELLO from TEST !HELLO from TEST !HELLO from TEST ! Hello from Test
            HELLO from TEST!HELLO from TEST!HELLO from TEST !HELLO from TEST !HELLO from TEST ! Hello from Test
            1 Kb data file is here!
          code: 200
          type: text/plain
      path: /
  status:
    message: 'Configuration for nginx-ingress/myapp was added or updated '
    reason: AddedOrUpdated
    state: Valid
kind: List
metadata:
  resourceVersion: ""
